module BitInt
  # An unsigned 8-bit integer
  class U8 < Base end

  # An unsigned 16-bit integer
  class U16 < Base end

  # An unsigned 32-bit integer
  class U32 < Base end

  # An unsigned 64-bit integer
  class U64 < Base end

  # An unsigned 128-bit integer
  class U128 < Base end

  # A signed 8-bit integer
  class I8 < Base end

  # A signed 16-bit integer
  class I16 < Base end

  # A signed 32-bit integer
  class I32 < Base end

  # A signed 64-bit integer
  class I64 < Base end

  # A signed 128-bit integer
  class I128 < Base end
end
