module BitInt
  # Refinements to +Integer+ for easy "+BitInt+ literals" (eg +puts(12.u8)+)
  module Refinements
    def u8: (?wrap: bool) -> U8
    def u16: (?wrap: bool) -> U16
    def u32: (?wrap: bool) -> U32
    def u64: (?wrap: bool) -> U64
    def u128: (?wrap: bool) -> U128

    def i8: (?wrap: bool) -> I8
    def i16: (?wrap: bool) -> I16
    def i32: (?wrap: bool) -> I32
    def i64: (?wrap: bool) -> I64
    def i128: (?wrap: bool) -> I128
  end
end
